name: Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop screenshots here or paste image URLs

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Select the environment where the bug occurred
      options:
        - Local development
        - Staging
        - Production
        - Other (specify in description)
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Browser and version (e.g., Chrome 120, Firefox 121)
      placeholder: Chrome 120

  - type: input
    id: os
    attributes:
      label: Operating System
      description: OS and version (e.g., Windows 11, macOS 14, Ubuntu 22.04)
      placeholder: Windows 11

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem, related issues, or suggestions
      placeholder: Add any other context, logs, or related issues here.

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have provided all the information requested above
          required: true
