import {
	Bookmark,
	BookmarkCheck,
	Copy,
	Crop,
	Delete,
	Download,
	Edit,
	Edit2,
	Filter,
	Minus,
	Move,
	Plus,
	PlusCircle,
	RefreshCw,
	Save,
	Scissors,
	Search,
	Share,
	Share2,
	Trash,
	Trash2,
	Upload,
} from 'lucide-react';

import type { IconItem } from './types';

export const actionsIcons: IconItem[] = [
	{ name: 'Plus', icon: Plus, category: 'Actions', keywords: ['add', 'create', 'new', 'plus'] },
	{
		name: 'PlusCircle',
		icon: PlusCircle,
		category: 'Actions',
		keywords: ['add', 'create', 'new', 'plus', 'circle'],
	},
	{ name: 'Minus', icon: Minus, category: 'Actions', keywords: ['remove', 'subtract', 'minus'] },
	{ name: 'Edit', icon: Edit, category: 'Actions', keywords: ['edit', 'modify', 'pencil'] },
	{
		name: 'Edit2',
		icon: Edit2,
		category: 'Actions',
		keywords: ['edit', 'modify', 'pencil', 'alt'],
	},
	{ name: 'Trash', icon: Trash, category: 'Actions', keywords: ['delete', 'remove', 'trash'] },
	{
		name: 'Trash2',
		icon: Trash2,
		category: 'Actions',
		keywords: ['delete', 'remove', 'trash', 'alt'],
	},
	{ name: 'Delete', icon: Delete, category: 'Actions', keywords: ['delete', 'remove'] },
	{ name: 'Copy', icon: Copy, category: 'Actions', keywords: ['copy', 'duplicate'] },
	{ name: 'Download', icon: Download, category: 'Actions', keywords: ['download', 'save'] },
	{ name: 'Upload', icon: Upload, category: 'Actions', keywords: ['upload', 'import'] },
	{ name: 'Share', icon: Share, category: 'Actions', keywords: ['share', 'send'] },
	{ name: 'Share2', icon: Share2, category: 'Actions', keywords: ['share', 'send', 'alt'] },
	{ name: 'Bookmark', icon: Bookmark, category: 'Actions', keywords: ['bookmark', 'save'] },
	{
		name: 'BookmarkCheck',
		icon: BookmarkCheck,
		category: 'Actions',
		keywords: ['bookmark', 'save', 'check'],
	},
	{ name: 'Filter', icon: Filter, category: 'Actions', keywords: ['filter', 'sort'] },
	{ name: 'Search', icon: Search, category: 'Actions', keywords: ['search', 'find'] },
	{ name: 'Save', icon: Save, category: 'Actions', keywords: ['save', 'store'] },
	{
		name: 'RefreshCw',
		icon: RefreshCw,
		category: 'Actions',
		keywords: ['refresh', 'reload', 'update'],
	},
	{ name: 'Crop', icon: Crop, category: 'Actions', keywords: ['crop', 'image', 'edit'] },
	{ name: 'Scissors', icon: Scissors, category: 'Actions', keywords: ['cut', 'scissors'] },
	{ name: 'Move', icon: Move, category: 'Actions', keywords: ['move', 'drag'] },
];
