import {
	Activity,
	Box,
	Camera,
	Cloud,
	CloudDownload,
	CloudUpload,
	Code,
	Command,
	Database,
	Grid,
	HardDrive,
	Layers,
	Layout,
	Power,
	Printer,
	Server,
	Smartphone,
	Sun,
	Terminal,
	Wifi,
	WifiOff,
	Zap,
} from 'lucide-react';

import type { IconItem } from './types';

export const systemIcons: IconItem[] = [
	{
		name: 'Activity',
		icon: Activity,
		category: 'System',
		keywords: ['activity', 'chart', 'graph'],
	},
	{ name: 'Zap', icon: Zap, category: 'System', keywords: ['zap', 'lightning', 'power'] },
	{ name: 'Power', icon: Power, category: 'System', keywords: ['power', 'on', 'off'] },
	{ name: 'Server', icon: Server, category: 'System', keywords: ['server', 'host', 'database'] },
	{
		name: 'Database',
		icon: Database,
		category: 'System',
		keywords: ['database', 'data', 'storage'],
	},
	{
		name: 'HardDrive',
		icon: HardDrive,
		category: 'System',
		keywords: ['harddrive', 'disk', 'storage'],
	},
	{ name: 'Cloud', icon: Cloud, category: 'System', keywords: ['cloud', 'storage', 'online'] },
	{
		name: 'CloudDownload',
		icon: CloudDownload,
		category: 'System',
		keywords: ['cloud', 'download', 'sync'],
	},
	{
		name: 'CloudUpload',
		icon: CloudUpload,
		category: 'System',
		keywords: ['cloud', 'upload', 'sync'],
	},
	{ name: 'Wifi', icon: Wifi, category: 'System', keywords: ['wifi', 'wireless', 'network'] },
	{ name: 'WifiOff', icon: WifiOff, category: 'System', keywords: ['wifi', 'off', 'disconnected'] },
	{ name: 'Code', icon: Code, category: 'System', keywords: ['code', 'programming', 'developer'] },
	{
		name: 'Terminal',
		icon: Terminal,
		category: 'System',
		keywords: ['terminal', 'command', 'cli'],
	},
	{
		name: 'Command',
		icon: Command,
		category: 'System',
		keywords: ['command', 'keyboard', 'shortcut'],
	},
	{ name: 'Layers', icon: Layers, category: 'System', keywords: ['layers', 'stack', 'overlay'] },
	{ name: 'Layout', icon: Layout, category: 'System', keywords: ['layout', 'grid', 'structure'] },
	{ name: 'Grid', icon: Grid, category: 'System', keywords: ['grid', 'table', 'matrix'] },
	{ name: 'Box', icon: Box, category: 'System', keywords: ['box', 'container', 'package'] },
	{ name: 'Printer', icon: Printer, category: 'System', keywords: ['printer', 'print'] },
	{
		name: 'Smartphone',
		icon: Smartphone,
		category: 'System',
		keywords: ['smartphone', 'mobile', 'phone'],
	},
	{ name: 'Camera', icon: Camera, category: 'System', keywords: ['camera', 'photo', 'capture'] },
	{ name: 'Sun', icon: Sun, category: 'System', keywords: ['sun', 'light', 'theme'] },
];
