import type { CategoryId } from './landing.types';

export const CATEGORIES = [
	{ id: 'root' as const, label: 'Root Components' },
	{ id: 'forms' as const, label: 'Forms' },
	{ id: 'data-display' as const, label: 'Data Display' },
	{ id: 'feedback' as const, label: 'Feedback' },
	{ id: 'navigation' as const, label: 'Navigation' },
	{ id: 'overlays' as const, label: 'Overlays' },
	{ id: 'media' as const, label: 'Media' },
	{ id: 'layout' as const, label: 'Layout' },
	{ id: 'hooks' as const, label: 'Hooks' },
	{ id: 'utilities' as const, label: 'Utilities' },
] as const satisfies readonly { id: CategoryId; label: string }[];

export const ALL_AVAILABLE_TAGS = [
	'form',
	'input',
	'validation',
	'date',
	'time',
	'file',
	'select',
	'button',
	'navigation',
	'overlay',
	'feedback',
	'data',
	'chart',
	'layout',
	'media',
	'hook',
	'utility',
	'text',
	'number',
	'email',
	'phone',
	'password',
	'search',
	'color',
	'currency',
	'tag',
	'rating',
	'slider',
	'toggle',
	'wizard',
	'table',
	'list',
	'card',
	'badge',
	'avatar',
	'code',
	'timeline',
	'tree',
	'alert',
	'toast',
	'progress',
	'spinner',
	'skeleton',
	'dialog',
	'modal',
	'tooltip',
	'popover',
	'menu',
	'tabs',
	'breadcrumbs',
	'pagination',
	'stepper',
	'image',
	'video',
	'carousel',
	'map',
	'animation',
	'scroll',
	'focus',
	'loading',
] as const;
